import Head from "next/head";
import Image from "next/image";
// import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Button, Link } from "@chakra-ui/react";
import { PageLayout } from "../components/PageLayout";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ALMA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <Box
          m={"5% 10%"}
          w={"80%"}
          bg={"#fff"}
          fontFamily={"en-maru-gothic"}
          fontSize={"20px"}
          fontWeight={700}
          borderRadius={"20px"}
          p={"60px 40px"}
        >
          <Box>🚨 基本的には個人利用を目的としております。</Box>
          <Box mt={"20px"}>
            👉 これよく使うなーというモノをメモ感覚でのせております。
          </Box>
          <Box mt={"20px"}>
            👉
            利用したいタイトルをクリックすることでコード等が展開し、表示されます。
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;コピー又はダウンロードの上ご利用ください。
          </Box>
          <Box mt={"20px"}>
            👉 コードにカーソルを合わせると右上にコピーボタンが表示されます。
          </Box>
          <Box mt={"20px"}>
            👉
            ツールをご利用の場合、参照先サイトの利用規約等をご理解の上でご利用ください。
          </Box>
          <Box mt={"20px"} textAlign={"center"}>
            どうでもいいですが
            <span className={styles.strongtxt}>「ALMA」=「ALL MASTER」</span>
            です。
          </Box>
        </Box>

        <Box
          display={"flex"}
          w={"80%"}
          m={"10% auto 0"}
          justifyContent={"space-around"}
        >
          <Link href="code">
            <Button
              bg={"#000"}
              color={"#fff"}
              fontFamily={"bungee, sans-serif"}
              fontWeight={"400"}
              w={"200px"}
              h={"70px"}
              fontSize={"30px"}
              _hover={{
                color: "#000",
                bg: "#fff",
              }}
            >
              CODE
            </Button>
          </Link>
          <Link>
            <Button
              bg={"#000"}
              color={"#fff"}
              fontFamily={"bungee, sans-serif"}
              fontWeight={"400"}
              w={"200px"}
              h={"70px"}
              fontSize={"30px"}
              _hover={{
                color: "#000",
                bg: "#fff",
              }}
            >
              TOOL
            </Button>
          </Link>
          <Link>
            <Button
              bg={"#000"}
              color={"#fff"}
              fontFamily={"bungee, sans-serif"}
              fontWeight={"400"}
              w={"200px"}
              h={"70px"}
              fontSize={"30px"}
              _hover={{
                color: "#000",
                bg: "#fff",
              }}
            >
              SITE
            </Button>
          </Link>
        </Box>
      </PageLayout>
    </>
  );
}
